### PR TITLE
Update to 8.1 and remove cruft

### PR DESCRIPTION
**Pull request by nimish**
Hi, this more or less deals with https://github.com/MOSEK/Mosek.pip/issues/18 -- I figured out a fix that works reasonably well. Also updates to 8.1 in the version.

### CODE REVIEW

**Comment by ulfworsoe** [comment]
Hi, it looks good, except you have eliminated the download directory. Yes, it is a hack, but the pip installer is often used to build an environment, run a job, and delete the environment repeatedly. If it has to download every time it causes a significant overhead. 
If you reintroduce the download dir I can merge.

**Comment by nimish** [comment]
OK, I will reintroduce this.

**Comment by nimish** [comment]
Hmm...I looked into reintroducing this, however there is no good generic way of getting a system-wide downloads cache folder. 

 I recommend caching the wheel (`python setup.py bdist_wheel` with `wheel` package installed) instead of the downloaded zip file. That's what we're doing.

If you really need to cache the zip itself, I would recommend using a caching proxy like squid in front of your build server.

**Comment by nimish** [comment]
OK, I have restored that bit. I really do think it should be removed and that Mosek ApS should simply publish whl files instead ;)

**Comment by ulfworsoe** [comment]
I will give wheel another try.

**Pull request merged**
